### ISSUE TITLE
No endpoints available for webhook service

### ISSUE THREAD

**Issue by yovelcohen** [milvus-io/milvus-operator#129]
Hi, I'm trying to create a template when using the operator, when I try to create my release I get an error:

```
Internal error occurred: failed calling webhook "mmilvuscluster.kb.io": Post "https://milvus-operator-webhook-service.milvus-operator.svc:443/mutate-milvus-io-v1alpha1-milvuscluster?timeout=10s": no endpoints available for service "milvus-operator-webhook-service"
```

I'm not really sure as to the source of the issue on this, but this is my yaml file:

```
apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: milvuscluster
  namespace: {{ .Values.global.namespace }}
spec:
  components:
    resources:
      limits:
        cpu: '4'
        memory: 16Gi
      requests:
        cpu: 200m
        memory: 512Mi
    dataCoord:
      replicas: 2
    dataNode:
      replicas: 2
    indexCoord:
      replicas: 1
    indexNode:
      replicas: 1
    proxy:
      replicas: 1
      serviceType: LoadBalancer
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 128Mi
    queryCoord:
      replicas: 3
    queryNode:
      replicas: 3
    rootCoord:
      replicas: 3
```

I'm using Argo if it has any meaning and running a cluster on EKS
