### ISSUE TITLE
can not connect external etcd using certficate and key

### ISSUE THREAD

**Issue by liaoyw** [milvus-io/milvus-operator#201]
We need to use external managed etcd for milvus meta store, but there's only `endpoints` for etcd according to https://milvus.io/docs/meta_storage_operator.md#Configure-etcd

Is there plan to support using certficate to connect ectd?
thanks.

**Comment by haorenfsa** [comment]
I just checked milvus configuration, it supports using etcd with certification  & key.  example is showed below:
``` yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
spec:
  # ... omit other fields
  config:
    etcd:
      ssl:
        enabled: true # Whether to support ETCD secure connection mode
        tlsCert: /path/to/etcd-client.pem # path to your cert file
        tlsKey: /path/to/etcd-client-key.pem # path to your key file
        tlsCACert: /path/to/ca.pem # path to your CACert file
        # TLS min version
        # Optional values: 1.0, 1.1, 1.2, 1.3。
        # We recommend using version 1.2 and above
        tlsMinVersion: 1.3
```



all configuration fields can be found here https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml#L17
