### ISSUE TITLE
Add check to avoid `null` in config fields

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus-operator#227]
For manifest like this:
```yaml
spec:
  config:
    common:
    #  security:
    #    authorizationEnabled: true
    etcd:
      rootPath: my-cluster
```
would assign `null` to `spec.config.common`.

Operator should be able to deny the call.
