### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by mxchinegod** [milvus-io/milvus-operator#276]
Where is the service account on line 13 of https://github.com/milvus-io/milvus-operator/blob/main/charts/milvus-operator/templates/job.yaml created?

ootb we do not have this service account. Is this supposed to motivate to make our own after deployment fails or is it a mistake?

**Comment by haorenfsa** [comment]
Here
 https://github.com/milvus-io/milvus-operator/blob/main/charts/milvus-operator/templates/serviceaccount.yaml

But its naming pattern is not exactly same with the one used in Job Template

**Comment by DylanAlloy** [comment]
https://github.com/milvus-io/milvus-operator/blob/main/charts/milvus-operator/templates/_helpers.tpl

line 68 breaks if you create a custom name for the service account in `installDependencies`. this is a common helm chart error people make when rushing their logic. 

unfortunately, if someone is say managing this project through argo or another CD pipeline which adds metadata to its own abstraction of your helm deployment, this logic will break altogether. 

how about just hardcoding a value since this is 100% generated and used by the helm chart?

**Comment by mxchinegod** [comment]
would you mind explaining what this chunk in _helpers is doing? I have custom name set in `installDependencies` and that is all it took to break it.

``` yaml
{{- define "chart.checkerServiceAccountName" -}}
{{- if .Values.installDependencies.enable }}
{{- if .Values.installDependencies.serviceAccount.create }}
{{- default (printf "%s-checker" (include "chart.fullname" .)) .Values.installDependencies.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
{{- end }}
```

``` yaml
# check and install the dependencies when enabled, this need an extra service account with privileged clusterroles
installDependencies:
  enable: true
  serviceAccount:
    # serviceAccount.create -- Specifies whether a service account should be created
    create: true
    # serviceAccount.annotations -- Annotations to add to the service account
    annotations: {}
    # serviceAccount.name -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "milvus-dep-sa"
```

is this concatenating the fullName arbitrarily to my custom name?
